### ISSUE TITLE
Fails when version ranges or wildcards are used

### ISSUE THREAD

**Issue by tom-englert** [sboulema/NuGetMonitor#1]
You can specify NuGet versions as ranges, e.g. `[1.0, 2.0)` or with wildcards, e.g. `1.*`. 

If any of these are present in a project, the extension stops doing anything.

Such versions should be ignored, also the package manager does not offer updates for those.

**Comment by sboulema** [comment]
Good point! Didn't even think about version ranges...

Fix looks very good! Would definitely merge as a PR :)
