### ISSUE TITLE
Shows delisted versions as available update

### ISSUE THREAD

**Issue by sboulema** [sboulema/NuGetMonitor#15]
The [QuestPDF](https://www.nuget.org/packages/QuestPDF) package has a high version numbered packaged (due to a typo) of 2202.8.2 (instead of 2022.8.2).

This version has been delisted as shown in the nuget API response:
https://api-v2v3search-0.nuget.org/search/query?q=packageid:questpdf&ignoreFilter=true&prerelease=true&take=100

    {
      "PackageRegistration": {
        "Id": "QuestPDF",
        "DownloadCount": 2309861,
        "Verified": false,
        "Owners": [],
        "PopularityTransfers": []
      },
      "Version": "2202.8.2",
      "NormalizedVersion": "2202.8.2",
      ...
      "IsLatestStable": false,
      "IsLatest": false,
      "Listed": false, <---------------
      ...
    },

**Comment by sboulema** [comment]
@tom-englert Maybe you have a solution?

The `NuGetVersion` model does not have a `Listed` property :(

**Comment by sboulema** [comment]
`IPackageSearchMetadata` has a `IsListed` property :)

**Comment by tom-englert** [comment]
We had a similar issue here:
https://github.com/Fody/PropertyChanged/issues/867

**Comment by tom-englert** [comment]
I think I have an idea, I will try to solve it.
