### ISSUE TITLE
Support for dotnet-tools.json?

### ISSUE THREAD

**Issue by VictorioBerra** [sboulema/NuGetMonitor#32]
Hello,

Can you add support for dotnet tools?

https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool

Thanks for the great extension! The default NuGet GUI does not work will with my Directory.Build.Props. NuGetMonitor works GREAT with it!

**Comment by tom-englert** [comment]
You are thinking of a command line tool?

**Comment by VictorioBerra** [comment]
@tom-englert Well the `dotnet-tools.json` has a list of tools with their nuget version:

```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "botsay": {
      "version": "1.0.0",
      "commands": [
        "botsay"
      ]
    },
    "dotnetsay": {
      "version": "2.1.3",
      "commands": [
        "dotnetsay"
      ]
    }
  }
}
```

Note `"version": "1.0.0",` is the NuGet package version.

If NuGetMonitor could check for this file, and check those versions against nuget, and read/write that file, that would be very helpful as I could just click a button and have my tools up to date.

**Comment by tom-englert** [comment]
Not sure if that's really fit into the scope of this tool, using a Visual Studio extension to update some global tools sounds strange.

What about writing a simple script (e.g. powershell) that calls `dotnet tool list`, and then for all tools calls `dot tool update`?

**Comment by VictorioBerra** [comment]
@tom-englert That is fair. I will say that global tools are not the same as tools in the `dotnet-tools.json`. Those are _local_ tools, that are essentially just NuGet packages that happen to live in a json file instead of csproj or props file. Some tools I use are [cake.tool](https://www.nuget.org/packages/Cake.Tool), and [minver](https://www.nuget.org/packages/minver-cli/5.0.0-beta.1). It is just as important to keep these build tools up to date as it is to keep nuget packages in a csproj or props file up to date.
