### ISSUE TITLE
[Feature Request] Check compatibility of upgrade with the project's current TargetFramework

### ISSUE THREAD

**Issue by jrdodds** [sboulema/NuGetMonitor#50]
### Background
I have a project targeting net8.0 that uses the [Microsoft.Build](https://www.nuget.org/packages/Microsoft.Build) package. Version 17.11.4 of the package supports net8.0. The next released version, 17.12.6, supports net9.0 and doesn't support net8.0.

NuGet Monitor showed the package update from 17.11.4 to 17.12.6. After updating the build produced a NuGet NU1701 warning:

> Package 'Microsoft.Build 17.12.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0'. This package may not be fully compatible with your project.

For this specific issue I changed the `PackageReference` to use `Version="17.11.*"`. The NU1701 warning is resolved and NuGet Monitor doesn't show the upgrade.

### Feature Request
NuGet Monitor is a great tool already but it would be nice if NuGet Monitor checked the compatibility of a package upgrade against the current `TargetFramework` and indicated that the upgrade is not just a change to the package version -- that the upgrade requires either changing the `TargetFramework` or changing the package version specification.

I don't have a suggestion on how this information might be reported by NuGet Monitor.

**Comment by tom-englert** [comment]
Also updating would become slow

**Comment by jrdodds** [comment]
> Also updating would become slow

Instead of checking as part of the check for updated versions, adding a verification step as part of performing the upgrade makes sense. The compatibility check would only be done when the user actually needs it.

If your point is that the compatibility check shouldn't be implemented at all because of the extra work and time, for my recent case a compatibility check would have saved me time. Is my example an unusual case? I don't know. If it is common enough then, overall, the compatibility check would save a developer's time.

**Comment by tom-englert** [comment]
I never had such an issue, so I would consider it a rare edge case.
However if you think it's worth spending time on this, you can provide a PR.

**Comment by 135620** [comment]
I came here specifically looking to see if this issue was being addressed. I don't think it's a rare edge case at all. I think it is very common to not move to the latest .Net Framework immediately upon release.

**Comment by tom-englert** [comment]
The intention behind this tool was to bypass all the checks to have fast update experience, and to defer the checks to the build process (see Readme).
If you want to have a checked update, just use the original NuGet Package Manager that comes with Visual Studio.

**Comment by jrdodds** [comment]
Oh - can I configure the Visual Studio NuGet Package Manager to check solutions on load and display an info bar? I wasn't aware it had that functionality.

**Comment by tom-englert** [comment]
@jrdodds no - did someone mention this?

**Comment by jrdodds** [comment]
From my perspective the fast update is a negative value. Package updates are not frequent enough that bypassing validation checks is a useful or helpful trade-off -- just the opposite. When possible, I prefer to find issues in the edit part of the edit-compile-test cycle.

@tom-englert I understand you view the fast update as integral and that an upgrade check is not compatible with bypassing validations. But for me, an improvement would be a configuration option to choose either the NuGet Monitor fast update or to invoke the NuGet Package Manager that comes with Visual Studio to perform the update with validation checks.

**Comment by tom-englert** [comment]
I have no idea what configuration you want - just open the one you like to work with.

**Comment by sboulema** [comment]
I understand the need for checks before doing/notifying about updates but as indicated all responsibility is deferred to the user and the build.

Else we would start checking for matching frameworks and the next moment we would be checking version conflicts between packages and we would have recreated the original NuGet Manager, slippery slope...

I do think this is a good situation where you can explicitly indicate not wanting to update with a pinned version and a justification as described in the readme.

**Comment by jrdodds** [comment]
> I have no idea what configuration you want - just open the one you like to work with.

As an example: In a notification of an update the `manage` link opens the NuGet Monitor package manager with the fast update. I never want that. I would like the link to open the Visual Studio NuGet package manager.

The monitoring functionality doesn't have to be tied to the fast update functionality. For me, the fast update is not a feature.

**Comment by jrdodds** [comment]
> Else we would start checking for matching frameworks and the next moment we would be checking version conflicts between packages and we would have recreated the original NuGet Manager, slippery slope...

Yeah -- agreed. Just give me the configuration option to use the original NuGet Manager in place of the NuGet Monitor package manager.

**Comment by sboulema** [comment]
Grab the new release! 🚀

**Comment by jrdodds** [comment]
Many thanks
:grinning:
