### ISSUE TITLE
Scanning too many sources

### ISSUE THREAD

**Issue by tom-englert** [sboulema/NuGetMonitor#6]
When my config looks like this, it should only read from exactly this repo:
```xml
  <packageSources>
    <clear />
    <add key="Artifactory" value="https://xxx/artifactory/api/nuget/nuget-release" />
  </packageSources>
```
However it's scanning all defaults, too.

You should not make assumptions about configs, but simply use exactly these repositories:
```c#
        var packageSourceProvider = new PackageSourceProvider(Settings.LoadDefaultSettings(_solutionDirectory));
        var sourceRepositoryProvider = new SourceRepositoryProvider(packageSourceProvider, Repository.Provider.GetCoreV3());
        var repositories = sourceRepositoryProvider.GetRepositories().ToArray();
```

**Comment by sboulema** [comment]
True, but having no NuGet.Config in a repo and going to the Visual Studio Package sources, will show the User and Computer level sources as enabled.
So only loading sources from the solution directory might actually miss sources.
But in your case I agree that the `<clear />` should be respected.

**Comment by tom-englert** [comment]
`Settings.LoadDefaultSettings` should handle this exactly the same way as `nuget.exe` does - that's what we need.

**Comment by sboulema** [comment]
Sorry! Missed the LoadDefaultSettings part. Will implement 😁
